version: 1

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: simple
    stream: ext://sys.stdout
  file_ddp_leech_db_images:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: logging/logs/ddp_leech_db_images.log

loggers:
  ddp_leech_db_images:
    level: DEBUG
    handlers: [console, file_ddp_leech_db_images]
    propagate: no
    
root:
  level: DEBUG
  handlers: [console]